### ISSUE TITLE
elasticsearch client timeout

### ISSUE THREAD

**Issue by garrickstapleszed** [arithmetric/lambda-stash#18]
When processing larger files, I was getting client timeouts. The default of 30 seconds wasn't enough.  I ended up adding `requestTimeout: Infinity` to esConfig in shipElasticsearch.js:
```
   var esConfig = {
    host: config.elasticsearch.host,
    requestTimeout: Infinity
  };
```

I figure I don't really care about the client's timeout since Lambda has it's own timeout.

Maybe this could be exposed as a config option?

**Comment by arithmetric** [comment]
Thanks, exposing the configuration makes sense to me.
