### ISSUE TITLE
Support for Encryption and Authentication

### ISSUE THREAD

**Issue by 0x4D31** [arithmetric/lambda-stash#2]
If I'm not mistaken, currently lambda-stash doesn't support SSL/TLS. It would be great if the shippers support that.
Supporting HTTP basic authentication is also needed (e.g. for using with Logstash HTTP input).

**Comment by arithmetric** [comment]
Agreed, it would be great to extend shipHttp to support HTTPS.

**Comment by 0x4D31** [comment]
Just to make sure, is shipElasticsearch uses HTTPS by default?

**Comment by arithmetric** [comment]
To use `https` when connecting to Elasticsearch, you should use `https://` in the `config.elasticsearch.host` configuration setting.
