### ISSUE TITLE
Can't install lambda-stash using npm

### ISSUE THREAD

**Issue by RomanCRS** [arithmetric/lambda-stash#24]
Seems like "http-aws-es" has been moved to different place. Therefore installation is failing.
I was able to install everything manually, but it takes much more time.
Can you fix it?
```
RomanCRS:lambda rchyr$ npm i lambda-stash
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/tphummel/http-aws-es.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rchyr/.npm/_logs/2018-05-18T08_47_40_421Z-debug.log
```

**Comment by arithmetric** [comment]
Hi @RomanCRS, I've updated the `http-aws-es` dependency in the `master` branch. Would you be able to test with that version?

**Comment by RomanCRS** [comment]
It is still failing. When I go to this link - https://www.versioneye.com/nodejs/lambda-stash/1.1.0 I still see that your app depends on - "github:tphummel/http-aws-es", but this repository doesn't exist or it is not publicly accessible. Could you please provide a release of the new version without dependencies to Github repository?

**Comment by arithmetric** [comment]
@RomanCRS, I've created the 2.0.0 release and published it to npm.

**Comment by RomanCRS** [comment]
@arithmetric Thank you! Now it is working fine.
