### ISSUE TITLE
Update lambda-stash to version 1.0.3 to include latest commit

### ISSUE THREAD

**Issue by nick4eva** [arithmetric/lambda-stash#8]
Hi @arithmetric,

We're using lambda-stash npm package to send logs from CloudWatch Logs to Elasticsearch via Logstash.
To do this we've created a custom handler (as described in https://www.npmjs.com/package/lambda-stash#features) but were surprised it doesn't work.

After investigation, I've found that version 1.0.2 doesn't include the latest commit which implementing custom handler, so we need to reference lambda-stash npm package like this: `"lambda-stash": "git+https://github.com/arithmetric/lambda-stash.git#d07ff21"` instead of this: `"lambda-stash": "^1.0.2"` (which is far more useful).

Could you please release version 1.0.3 based on latest source code?

**Comment by arithmetric** [comment]
@nick4eva Thanks for the reminder. I've published it as 1.1.0.
